[general]
import = [
    "~/.cache/wal/colors-alacritty.toml"
]

[font]
normal = { family = "DepartureMono Nerd Font Mono", style = "Regular" }
bold = { family = "DepartureMono Nerd Font Mono", style = "Regular" }
italic = { family = "DepartureMono Nerd Font Mono", style = "Regular" }

size = 14.0

offset = { x = 0, y = 0 }
