[colors]
background = {background}
background-alt = {color0}
foreground = {foreground}
disabled = {color8}

; Accent colors
primary = {color4}
secondary = {color5}
tertiary = {color6}
alert = {color1}

; Additional colors
yellow = {color3}
blue = {color4}
aqua = {color6}
purple = {color5}
red = {color1}
orange = {color9}
