;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================

include-file = ~/.cache/wal/colors-polybar.ini

[bar/mybar]
width = 100%
height = 24pt
radius = 6

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 3pt
border-size = 4pt
border-color = #00000000

padding-left = 0
padding-right = 1
module-margin = 1

separator = |
separator-foreground = ${colors.disabled}

; Updated Font
font-0 = DepartureMono Nerd Font Mono:style=Regular;2

; Updated Module Layout
modules-left = xworkspaces xwindow
modules-center = date
modules-right = systray pulseaudio wifi filesystem memory cpu gpu

cursor-click = pointer
cursor-scroll = ns-resize
enable-ipc = true


; --- MODULES ---

[module/systray]
type = internal/tray
format-margin = 8pt
tray-spacing = 16pt

[module/xworkspaces]
type = internal/xworkspaces
label-active = %name%
label-active-background = ${colors.background-alt}
label-active-underline= ${colors.primary}
label-active-padding = 1
label-occupied = %name%
label-occupied-padding = 1
label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1
label-empty = %name%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1

[module/xwindow]
type = internal/xwindow
label = %title:0:60:...%

[module/filesystem]
type = internal/fs
interval = 25
mount-0 = /
format-mounted-prefix = "󰋊 "
format-mounted-prefix-foreground = ${colors.yellow}
label-mounted = %percentage_used%%
label-unmounted = %mountpoint% not mounted
label-unmounted-foreground = ${colors.disabled}

[module/pulseaudio]
type = internal/pulseaudio
format-volume = <ramp-volume> <label-volume>
label-volume = %percentage%%
ramp-volume-0 = 
ramp-volume-1 = 
ramp-volume-2 = 
format-volume-foreground = ${colors.blue}
label-muted = 󰝟
label-muted-foreground = ${colors.disabled}

[module/memory]
type = internal/memory
interval = 2
format-prefix = " "
format-prefix-foreground = ${colors.aqua}
label = %percentage_used:2%%

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = " "
format-prefix-foreground = ${colors.purple}
label = %percentage:2%%

[module/gpu]
type = custom/script
exec = nvidia-smi --query-gpu=utilization.gpu --format=csv,noheader,nounits
interval = 2
format-prefix = "󰢮 "
format-prefix-foreground = ${colors.red}
label = %output%%

[module/date]
type = internal/date
interval = 1
date = %H:%M
date-alt = %Y-%m-%d %H:%M:%S
label = %date%
label-foreground = ${colors.primary}

[module/wifi]
type = internal/network
interface = wlan0
interval = 3
format-connected = <ramp-signal> <label-connected>
label-connected = %signal%%
format-connected-foreground = ${colors.orange}
ramp-signal-0 = 󰤯
ramp-signal-1 = 󰤟
ramp-signal-2 = 󰤢
ramp-signal-3 = 󰤥
ramp-signal-4 = 󰤨
format-disconnected = 󰤭
format-disconnected-foreground = ${colors.disabled}

[settings]
screenchange-reload = true
pseudo-transparency = true
